### ISSUE TITLE
lhlo reduce to linalg reduce - unnecessary initialization / conditional in block

### ISSUE THREAD

**Issue by bondhugula** [google/iree#2130]
I have IREE head from 778230076df35c1acbd2745be8366836ac0a69a4 (Jun 5). For the first test case example in iree/compiler/Conversion/HLOToLinalg/test/reduce.mlir, I notice iree-opt with -iree-codegen-hlo-to-linalg-on-buffers emitting:

```
#map0 = affine_map<(d0, d1) -> (d1, d0)>
#map1 = affine_map<(d0, d1) -> ()>
#map2 = affine_map<(d0, d1) -> (d0)>
  func @reduction_entry() {
    %0 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret0} : memref<4xf32>
    %c0 = constant 0 : index
    %1 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg0} : memref<5x4xf32>
    %2 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg1} : memref<f32>
    %cst = constant 0.000000e+00 : f32
    linalg.fill(%0, %cst) : memref<4xf32>, f32
    linalg.indexed_generic {args_in = 2 : i64, args_out = 1 : i64, indexing_maps = [#map0, #map1, #map2], iterator_types = ["parallel", "reduction"]} %1, %2, %0 {
    ^bb0(%arg0: index, %arg1: index, %arg2: f32, %arg3: f32, %arg4: f32):  // no predecessors
      %c0_0 = constant 0 : index
      %true = constant true
      %3 = cmpi "eq", %arg1, %c0_0 : index
      %4 = and %true, %3 : i1
      %5 = select %4, %arg3, %arg4 : f32
      %6 = addf %arg2, %5 : f32
      linalg.yield %6 : f32
    }: memref<5x4xf32>, memref<f32>, memref<4xf32>
    return
  }
```
The block body is doing a comparison so that for the first iteration of the reduction loop, you read in the init value (in %2 / %arg3). However, there is also a fill with zero. If there is a conditional to take care of the init, the fill isn't needed? Conversely, if the init is actually done with %2[] instead of %cst, the conditional in the body is actually not need - the same operand %0 could be sent as the second one, and this would be the cleaner/faster output. When you convert this to loops (either scf.for or affine.for), the generated code now has a conditional in the body and the initialization is redundant.

```
#map0 = affine_map<(d0) -> (d0)>
#map1 = affine_map<() -> (0)>
#map2 = affine_map<() -> (5)>
#map3 = affine_map<(d0, d1) -> (d0, d1)>
#map4 = affine_map<() -> ()>
#map5 = affine_map<() -> (4)>


module {
  func @foo() {
    %cst = constant 0.000000e+00 : f32
    %c0 = constant 0 : index
    %cst_0 = constant true
    %0 = alloc() : memref<5xf32>
    %1 = alloc() : memref<5x4xf32>
    %2 = alloc() : memref<f32>
    affine.for %arg0 = 0 to 5 {
      affine.store %cst, %0[%arg0] : memref<5xf32>
    }
    affine.for %arg0 = 0 to 4 {
      affine.for %arg1 = 0 to 5 {
        %3 = affine.load %1[%arg1, %arg0] : memref<5x4xf32>
        %4 = affine.load %2[] : memref<f32>
        %5 = affine.load %0[%arg0] : memref<5xf32>
        %6 = cmpi "eq", %arg1, %c0 : index
        %7 = and %6, %cst_0 : i1
        %8 = select %7, %4, %5 : f32
        %9 = addf %3, %8 : f32
        affine.store %9, %0[%arg0] : memref<5xf32>
      }
    }
    return
  }
}
```
@MaheshRavishankar

**Comment by benvanik** [comment]
Removing the initialization would be really nice! Right now that fill op ends up getting special handling that introduces some really nasty synchronization on the GPU:
https://github.com/google/iree/blob/master/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp#L185-L198

**Comment by bondhugula** [comment]
> Removing the initialization would be really nice! Right now that fill op ends up getting special handling that introduces some really nasty synchronization on the GPU:
> https://github.com/google/iree/blob/master/iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp#L185-L198

The initialization (fill op) can go away without changing anything given the conditional inside - it was an oversight perhaps? The data parallel dimensions' sizes I assume have to match 1:1 with the output's and so the reduction nest does cover the initialization.

But are you okay with the `cmpi` inside the loop body? The `cmpi` can be removed by fixing the initialization --- the values to initialize should come from %2 (and not %cst). For several things downstream, not having a compare is the better choice - there wouldn't be unnecessary predication just due to the first iteration.

On another note, looking at the generated affine nest, the loop indices are all wrong - they are flipped. The generated output for standard loops - scf.for has the same issue as well - looks like another bug.

I was going to adapt this code to complete the lhlo to linalg lowering for reduce_op but I guess this can be fixed as well while on it.

**Comment by benvanik** [comment]
I'll let @MaheshRavishankar comment as he knows much more about the particular implementation but I believe you're correct. We had discussed this awhile ago but I never quite understood why the fill was required (it's not in many other reduce implementations). It may have been a limitation of some part of the system prior to some linalg/affine/etc improvements that now make it possible.

**Comment by antiagainst** [comment]
Ah, thanks @bondhugula! I think you are right that the `linalg.fill` is redundant for this case. I added the buffer fill with `linalg.fill` in blanket previously to support linalg ops with reduction iterator. It avoids us to read uninitialized buffer for cases like linalg.matmul when converting from HLO dot op. But here the source reduction op carries the initial value by itself... So I think we can remove the buffer fill.

**Comment by hanhanW** [comment]
This was the first initialization issue we hit, so in the beginning I used indexed_generic op to handle the initial value. In the beginning, we didn't support multiple Linalg op in a single dispatch function, so we needed an indexed_generic op to do the first computation right. With Lei's patch, now we can rely on `linalg.fill` to initial buffers. I think we can keep the fill op and remove all comparison ops inside the block. It looks more efficient to me? I think we want to fill the initial value carried by `xla_hlo.reduce` first, and then apply the reduction function.

I can help on fixing it, what do you think?

**Comment by hanhanW** [comment]
plus, it would be like how we handled in `xla_hlo.reduce_window` op.

(btw, I think there is a bug in initialization of `reduce_window`. The buffers are always filled with zero, but it should be initial value instead. I forgot to file an issue and fix it...)

**Comment by bondhugula** [comment]
> plus, it would be like how we handled in `xla_hlo.reduce_window` op.
> 
> (btw, I think there is a bug in initialization of `reduce_window`. The buffers are always filled with zero, but it should be initial value instead. I forgot to file an issue and fix it...)

That's right - it isn't being initialized with the right value. The same for `reduce` once you've removed the conditional from the nest body.

**Comment by bondhugula** [comment]
> This was the first initialization issue we hit, so in the beginning I used indexed_generic op to handle the initial value. In the beginning, we didn't support multiple Linalg op in a single dispatch function, so we needed an indexed_generic op to do the first computation right. With Lei's patch, now we can rely on `linalg.fill` to initial buffers. I think we can keep the fill op and remove all comparison ops inside the block. It looks more efficient to me? I think we want to fill the initial value carried by `xla_hlo.reduce` first, and then apply the reduction function.
> 
> I can help on fixing it, what do you think?

Sure - if you'd like to take it up. Btw, there is another bug - the access functions are incorrect when the linalg reduce op is converted to loops. I think the linalg op being created here has incorrect indexing maps - something to check.

**Comment by bondhugula** [comment]
> This was the first initialization issue we hit, so in the beginning I used indexed_generic op to handle the initial value. In the beginning, we didn't support multiple Linalg op in a single dispatch function, so we needed an indexed_generic op to do the first computation right. With Lei's patch, now we can rely on `linalg.fill` to initial buffers. I think we can keep the fill op and remove all comparison ops inside the block. It looks more efficient to me? I think we want to fill the initial value

In general, it's more efficient this way (for CPUs typically and where you don't want a branch/conditional inside), but it all depends on where the generated code is going. @benvanik commented above he preferred the conditional guard inside and no init outside.

**Comment by antiagainst** [comment]
The `linalg.fill` is a generic way to initialize buffers without invoking cross-runtime-kernel optimizations. But yes as Ben pointed out, it will become a separate kernel at the moment so there is synchronization overhead on GPU. We discussed previously that we can potentially have `vkCmdFillBuffer` for the `linalg.fill` here too but I implemented the current way given that splitting a dispatch region into multiple kernel launches is needed anyway for other GPU feasibility purposes in the future. (Note that dispatch region discovery does not consider architecture specific requirements; it's just trying to discover maximal concurrency where possible.)

But on the other side, I think GPU does not perfer branchy code even than CPU. :) Both approaches have their wins. I guess a possible way to decide is to try both (I think both are easy given we just delete the code for the other approach) and run over `iree-benchmark-module` to see which wins.

**Comment by benvanik** [comment]
the vkCmdFillBuffer will still have the same synchronization issue - every byte in the output will need to be written and made available prior to any dispatch of the actual reduction beginning.

There really is no reason to need a fill. Any algorithm we have that needs it is likely not even close to the state of the art algorithms known for reduction. Here's a relatively ancient nvidia doc (2006!):
https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf?ncid=afm-chs-44270&ranMID=44270&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-xPdoYhK.FBySiKSp6rCAJg

![image](https://user-images.githubusercontent.com/75337/84078575-060a2600-a98e-11ea-8ed6-a6114c3be99c.png)

![image](https://user-images.githubusercontent.com/75337/84078671-233ef480-a98e-11ea-9d8e-82ed50ff17a7.png)

Note that g_idata is never written and g_odata is never read. The initial value of g_odata does not matter (as it shouldn't), and no fill is required. When HLO initial-value semantics are required a non-divergent check can be inserted to handle that; for example, the last line writing to g_odata can be
```
  // for the last step (the dispatch writing out the final buffer value) perform
  // the initial-value operation
  // note that we can just pass last_step/initial_value as a push constant and
  // the branch is non-divergent
  if (tid == 0) g_odata[blockIdx.x] = last_step ? max(sdata[0], initial_value) : sdata[0];
```

(there's no harm in always emitting that so that we can dedupe kernels, and there's very few things faster on a GPU than a branch on a uniform register that is uniformly taken across all invocations)

I feel like with mahesh working on adding workspace memory in #2135 this kind of kernel should be possible to emit to SPIR-V. If there's no clean HLO > linalg > SPIR-V path then it's probably worth handling it special. Taking a day to lower this directly and then doing the research for how to best represent this in linalg will help us get to a reasonable baseline.

**Comment by antiagainst** [comment]
Oh sorry I think my previous reply focuses a bit on what we can do relatively trivially. Ben, you are absolutely right that we should look at and implement the tree-based reduction. It's just that we've gotten quite a few other stuff to handle that I don't mind to just delete a few line of code to give use a small improvement and then come back to this nicer solution later. ;)

**Comment by benvanik** [comment]
Let's not spend a single cycle more on this - linalg-on-tensors and associated improvements are the way forward.
