### ISSUE TITLE
Add support for `jax.lax.while`/`mhlo.while` for ASR.

### ISSUE THREAD

**Issue by phoenix-meadowlark** [google/iree#9499]
### Request description

IREE needs to support `jax.lax.while` in order to support inference for JAX ASR models.

Toy examples fail with the error that `mhlo.while` is explicitly marked illegal. 

For example:

```python
import jax
import jax.numpy as jnp

def cond_fun(state):
  i, _ = state
  return i < 8

def body_fun(state):
  i, array = state
  return (i + 1, array + i)

def while_loop(x):
  return jax.lax.while_loop(cond_fun, body_fun, (0, x))

jax.jit(while_loop, device=jax.devices("iree")[0])(jnp.arange(3))
```

Produces the following error:

```
CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<ipython-input-28-6e621557edc0>:10:1: error: failed to legalize operation 'mhlo.while' that was explicitly marked illegal
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
compilation failed
```

And reproducer:

```mlir
// configuration: -pass-pipeline='func.func(iree-top-level-scf-to-cfg,iree-mhlo-to-mhlo-preprocessing{order-conv-features=true},canonicalize{  max-iterations=10 region-simplify=true top-down=true},shape-to-shape-lowering), convert-shape-to-std, func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true}), inline{default-pipeline=canonicalize{  max-iterations=10 region-simplify=true top-down=true} max-iterations=4 }, iree-util-demote-i64-to-i32, iree-util-demote-f64-to-f32, func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse,iree-mhlo-to-linalg-ext,iree-mhlo-to-linalg-on-tensors), reconcile-unrealized-casts, func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true}), iree-mhlo-verify-compiler-input-legality, iree-import-public, iree-sanitize-module-names, iree-abi-wrap-entry-points, inline{default-pipeline=canonicalize{  max-iterations=10 region-simplify=true top-down=true} max-iterations=4 }, func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse), symbol-dce, iree-util-demote-f64-to-f32, func.func(iree-flow-convert-conv2d-1x1-to-matmul,iree-verify-input-legality),util.initializer(iree-flow-convert-conv2d-1x1-to-matmul,iree-verify-input-legality), linalg-named-op-conversion, iree-flow-expand-tensor-shapes, iree-util-fixed-point-iterator{max-iterations=10 pipeline=func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses),iree-util-apply-patterns,iree-util-fold-globals,func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse),util.initializer(canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse)}, func.func(iree-flow-pad-tensor-to-subtensor-insert,convert-elementwise-to-linalg,linalg-fold-unit-extent-dims{fold-one-trip-loops-only=false},iree-flow-interchange-generic-ops,resolve-shaped-type-result-dims,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse,iree-flow-fusion-of-tensor-ops,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse,iree-flow-split-reduction-ops,iree-flow-interchange-generic-ops,iree-flow-dispatch-linalg-on-tensors-pass,iree-flow-capture-dispatch-dynamic-dims,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse),util.initializer(iree-flow-pad-tensor-to-subtensor-insert,convert-elementwise-to-linalg,linalg-fold-unit-extent-dims{fold-one-trip-loops-only=false},iree-flow-interchange-generic-ops,resolve-shaped-type-result-dims,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse,iree-flow-fusion-of-tensor-ops,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse,iree-flow-split-reduction-ops,iree-flow-interchange-generic-ops,iree-flow-dispatch-linalg-on-tensors-pass,iree-flow-capture-dispatch-dynamic-dims,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse), iree-flow-initialize-empty-tensors, iree-flow-outline-dispatch-regions, flow.executable(iree-util-strip-debug-ops),func.func(canonicalize{  max-iterations=10 region-simplify=true top-down=true}),util.initializer(canonicalize{  max-iterations=10 region-simplify=true top-down=true}), iree-flow-deduplicate-executables, flow.executable(canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse),func.func(iree-flow-cleanup-tensor-shapes,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse),util.initializer(iree-flow-cleanup-tensor-shapes,canonicalize{  max-iterations=10 region-simplify=true top-down=true},cse), symbol-dce, iree-stream-verify-input, iree-stream-outline-constants, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-stream-conversion, iree-stream-verify-lowering-to-tensors, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-util-combine-initializers, func.func(iree-stream-encode-host-tensors),stream.executable(iree-stream-encode-device-tensors),util.initializer(iree-stream-encode-host-tensors), iree-stream-materialize-builtins, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, func.func(iree-stream-materialize-copy-on-write),util.initializer(iree-stream-materialize-copy-on-write), iree-stream-elide-async-copies, iree-stream-refine-usage, func.func(iree-stream-schedule-execution,iree-stream-schedule-concurrency),util.initializer(iree-stream-schedule-execution,iree-stream-schedule-concurrency), iree-stream-propagate-timepoints, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-stream-verify-lowering-to-async, func.func(iree-stream-schedule-allocation,iree-stream-pack-constants,iree-stream-pack-allocations,iree-stream-layout-slices),util.initializer(iree-stream-schedule-allocation,iree-stream-pack-constants,iree-stream-pack-allocations,iree-stream-layout-slices), iree-stream-propagate-subviews, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-stream-verify-lowering-to-cmd, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-stream-fuse-dispatch-bindings{alias-mutable-bindings=false}, iree-stream-pack-dispatch-operands, cse, iree-stream-fold-uniform-operands, iree-stream-annotate-dispatch-arguments, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, symbol-dce, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-hal-assign-target-devices{targets=dylib}, iree-hal-verify-target-environment, iree-hal-materialize-interfaces, hal.executable(iree-hal-translate-executables), iree-hal-conversion, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, iree-hal-link-executables, iree-hal-resolve-entry-point-ordinals, iree-hal-materialize-resource-caches, func.func(iree-hal-inline-device-switches),util.initializer(iree-hal-inline-device-switches), iree-hal-memoize-device-queries, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, func.func(iree-hal-elide-redundant-commands),util.initializer(iree-hal-elide-redundant-commands), lower-affine, iree-util-combine-initializers, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, func.func(iree-util-simplify-global-accesses),util.initializer(iree-util-simplify-global-accesses), iree-util-apply-patterns, iree-util-fold-globals, iree-util-fuse-globals, hal.executable(iree-hal-serialize-executables), symbol-dce, func.func(affine-loop-coalescing,loop-invariant-code-motion,convert-scf-to-cf),util.initializer(loop-invariant-code-motion,convert-scf-to-cf), canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, iree-vm-conversion, vm.module(iree-vm-hoist-inlined-rodata,iree-vm-deduplicate-rodata,iree-vm-global-initialization), inline{default-pipeline=canonicalize{  max-iterations=10 region-simplify=true top-down=true} max-iterations=4 }, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, cse, vm.module(iree-vm-drop-empty-module-initializers), symbol-dce, vm.module(iree-vm-sink-defining-ops), iree-util-drop-compiler-hints' -verify-each
#loc0 = loc(unknown)
module @jit_while_loop.60 {
  func.func public @main(%arg0: tensor<3xi32> loc(unknown)) -> (tensor<i32>, tensor<3xi32>) {
    %0 = mhlo.constant dense<0> : tensor<i32> loc(#loc0)
    %1:2 = mhlo.while(%iterArg = %0, %iterArg_0 = %arg0) : tensor<i32>, tensor<3xi32>
     cond {
      %2 = mhlo.constant dense<8> : tensor<i32> loc(#loc1)
      %3 = "mhlo.compare"(%iterArg, %2) {compare_type = #mhlo<"comparison_type SIGNED">, comparison_direction = #mhlo<"comparison_direction LT">} : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc2)
      "mhlo.return"(%3) : (tensor<i1>) -> () loc(#loc1)
    } do {
      %2 = mhlo.constant dense<1> : tensor<i32> loc(#loc1)
      %3 = mhlo.add %iterArg, %2 : tensor<i32> loc(#loc3)
      %4 = mhlo.convert %iterArg : tensor<i32> loc(#loc4)
      %5 = "mhlo.broadcast_in_dim"(%4) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<3xi32> loc(#loc3)
      %6 = mhlo.add %iterArg_0, %5 : tensor<3xi32> loc(#loc3)
      "mhlo.return"(%3, %6) : (tensor<i32>, tensor<3xi32>) -> () loc(#loc1)
    } loc(#loc1)
    return %1#0, %1#1 : tensor<i32>, tensor<3xi32> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(while_loop)/jit(main)/while[cond_nconsts=0 body_nconsts=0]"("<ipython-input-28-6e621557edc0>":10:1))
#loc2 = loc("jit(while_loop)/jit(main)/while/cond/lt"("<ipython-input-28-6e621557edc0>":3:1))
#loc3 = loc("jit(while_loop)/jit(main)/while/body/add"("<ipython-input-28-6e621557edc0>":7:1))
#loc4 = loc("jit(while_loop)/jit(main)/while/body/convert_element_type[new_dtype=int32 weak_type=False]"("<ipython-input-28-6e621557edc0>":7:1))
```

A more realistic example created by removing the unsupported scatter operations (#9456) in the ASR decoder can be found in [this gist](https://gist.github.com/phoenix-meadowlark/d81ea02abca18eef78d0829a7a714880).

Related to #9295.

### What component(s) does this issue relate to?

Frontends, MLIR

**Comment by jpienaar** [comment]
Looking at it, this should be handled by passes in buildXLACleanupPassPipeline() and this fails during pipeline constructed by buildMHLOInputConversionPassPipeline() which would happen if InputDialectOptions::Type::mhlo path is followed. Adding mhlo::createLegalizeControlFlowPass to buildMHLOInputConversionPassPipeline should resolve that. Let me test.

**Comment by phoenix-meadowlark** [comment]
I'm still getting the same error when I try to compile via JAX (with #9525 applied) or directly using `iree-compile` on the reproducer above:

```shell
iree/tools/iree-compile \
  --iree-input-type=mhlo \
  --iree-vm-bytecode-module-output-format=flatbuffer-binary \
  --iree-hal-target-backends=dylib \
  --iree-mlir-to-vm-bytecode-module \
  --iree-llvm-embedded-linker-path=iree/tools/iree-lld \
  --mlir-print-debuginfo \
  --mlir-pass-pipeline-crash-reproducer=/tmp/iree/core-reproducer.mlir \
  /tmp/jax_while.mlir
```

```mlir
<ipython-input-28-6e621557edc0>:10:1: error: failed to legalize operation 'mhlo.while' that was explicitly marked illegal
<ipython-input-28-6e621557edc0>:10:1: note: see current operation: %6:2 = "mhlo.while"(%5, %arg0) ({
^bb0(%arg1: tensor<i32> loc("/tmp/jax_while.mlir":6:23), %arg2: tensor<3xi32> loc("/tmp/jax_while.mlir":6:38)):
  %7 = "mhlo.compare"(%arg1, %3) {compare_type = #mhlo<"comparison_type SIGNED">, comparison_direction = #mhlo<"comparison_direction LT">} : (tensor<i32>, tensor<i32>) -> tensor<i1> loc("jit(while_loop)/jit(main)/while/cond/lt"("<ipython-input-28-6e621557edc0>":3:1))
  "mhlo.return"(%7) : (tensor<i1>) -> () loc("jit(while_loop)/jit(main)/while[cond_nconsts=0 body_nconsts=0]"("<ipython-input-28-6e621557edc0>":10:1))
}, {
^bb0(%arg1: tensor<i32> loc("/tmp/jax_while.mlir":6:23), %arg2: tensor<3xi32> loc("/tmp/jax_while.mlir":6:38)):
  %7 = "mhlo.add"(%arg1, %1) : (tensor<i32>, tensor<i32>) -> tensor<i32> loc("jit(while_loop)/jit(main)/while/body/add"("<ipython-input-28-6e621557edc0>":7:1))
  %8 = "mhlo.broadcast_in_dim"(%arg1) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>) -> tensor<3xi32> loc("jit(while_loop)/jit(main)/while/body/add"("<ipython-input-28-6e621557edc0>":7:1))
  %9 = "mhlo.add"(%arg2, %8) : (tensor<3xi32>, tensor<3xi32>) -> tensor<3xi32> loc("jit(while_loop)/jit(main)/while/body/add"("<ipython-input-28-6e621557edc0>":7:1))
  "mhlo.return"(%7, %9) : (tensor<i32>, tensor<3xi32>) -> () loc("jit(while_loop)/jit(main)/while[cond_nconsts=0 body_nconsts=0]"("<ipython-input-28-6e621557edc0>":10:1))
}) : (tensor<i32>, tensor<3xi32>) -> (tensor<i32>, tensor<3xi32>) loc("jit(while_loop)/jit(main)/while[cond_nconsts=0 body_nconsts=0]"("<ipython-input-28-6e621557edc0>":10:1))
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertMHLOToLinalgOnTensors` on 'func.func' operation: @main]: reproducer generated at `/tmp/iree/core-reproducer.mlir`
```

I applied #9525 to the Google-internal version of IREE. I'm not sure how frequently that is synced with the GitHub version, so it could be an issue of needing to apply multiple patches, but I didn't see anything obviously deficient in the Bazel dependencies.

**Comment by phoenix-meadowlark** [comment]
I got an OSS dev environment set up and it looks like this is lowering correctly, so my hacky Google-internal patch was probably just poorly hacked. Thanks!
